# Header
menu:
  回到主页: /
  所有文章: /archives
  # view案列: /Demo
  #笔随心行: /say/笔随心行

# SubNav
subnav:
  github: "https://github.com/CracKerMe"
  zhihu: "https://www.zhihu.com/people/awebman"
  weibo: "http://weibo.com/crackerme"
  #twitter: "https://twitter.com/DragonKnightLOL"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
#mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
#google_analytics: ''
favicon: http://7xjdah.com1.z0.glb.clouddn.com/favicon.ico

#你的头像url
avatar: http://7xjdah.com1.z0.glb.clouddn.com/pic2016051107.jpg
#是否开启分享
share_jia: false
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: false
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
 None: www.baidu.com

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: NickName：AppleSun；MyQQ：1160948478；CellPhone：18861858309
